### ISSUE TITLE
【第 15 期】流式计算入门-以Apache Flink为例

### ISSUE THREAD

**Issue by arcosx** [NUAA-Open-Source/weekly#3]
## 简介 
数据流是指在时间分布和数量上无限的一系列动态数据集合体，流式计算，就是对数据流进行处理，是实时计算。随着大数据时代的到来，5G，物联网的爆发，数据的实时性直接影响数据的价值，传统的批量处理无法满足大家对数据时效性的要求。一些流式计算的框架，平台，产品相继诞生。例如：Storm，Spark Streaming，Apache Flink 等。
本次分享介绍一些入门的流式计算概念，着重讲现在热门的流式计算框架 Flink ，也会讲与 Flink 相关的技术框架，如 Apache Kafka，Apache Doris等。会通过两个小demo，将这些组件串起来。
内容比较浅显，适合想了解流式计算的同学。

## 大纲
1. 分享背景(流式计算应用场景,相关框架,价值等)
2. Flink 流式计算框架简要入门
3. demo1 
4. demo2

## 讲者

@arcosx ，南京航空航天大学 计算机科学与技术系 2019届毕业生，就职于某互联网公司。

## 分享时间

2020-03-08 19:00 UTC+8

## 分享地址

Invite Only. If you want to be invited, please contact A2OS core team members.

## 预备材料
1. https://flink.apache.org/
2. https://kafka.apache.org/
3. https://github.com/flink-china/flink-training-course
## 归档资料

1. Flink 中文社区：https://ververica.cn/corporate-practice/
2. Flink 文档：https://ci.apache.org/projects/flink/flink-docs-release-1.10/

**Comment by Triple-Z** [comment]
@arcosx 归档 Slides 需要再补充一下~

**Comment by arcosx** [comment]
https://ververica.cn/developers/flink-training-course1/
PPT内容节选自官方提供中文教程，就不重复上传了，想了解的同学在这里下载观看对应视频，PPT即可。
